export interface Location {
  name: string;
  areas: string[];
}

export interface RegionData {
  [key: string]: Location;
}

export const TRINIDAD_TOBAGO_LOCATIONS: RegionData = {
  Central: {
    name: 'Central',
    areas: [
      'Balmain',
      'Balmain Gardens',
      'California',
      'Carapichaima',
      'Caroni',
      'Central Park',
      'Chaguanas',
      'Charlieville',
      'Chase Village',
      'Chin Chin',
      'Couva',
      'Cunupia',
      'Edinburgh',
      'Endeavour',
      'Esperanza',
      'Exchange',
      'Felicity',
      'Flanagin Town',
      'Freeport',
      'Gran Couva',
      'Jerningham Junction',
      'Kelly Village',
      'Lange Park',
      'Longdenville',
      'Mamoral',
      'Piparo',
      'Point Lisas',
      'Preysal',
      'Reform',
      'Roystonia',
      'Savonetta',
      'St. Helena',
      'Tabaquite',
      'Talparo',
      "Todd's Road",
      'Tortuga',
      'Waterloo',
    ],
  },
  'North East': {
    name: 'North East',
    areas: [
      'Aranguez',
      'Arima',
      'Arouca',
      'Balandra',
      'Bamboo',
      'Barataria',
      'Biche',
      'Blanchisseuse',
      'Brazil',
      'Caura',
      'Champs Fleurs',
      'Cumaca',
      'Cumuto',
      'Curepe',
      "D'Abadie",
      'El Dorado',
      'El Socorro',
      'Grand Rivière',
      'La Fillette',
      'La Horquetta',
      'Las Cuevas',
      'Las Lomas',
      'Lopinot',
      'Macoya',
      'Maloney',
      'Manzanilla',
      'Maracas',
      'Maracas Bay',
      'Maracas Valley',
      'Matura',
      'Mausica',
      'Mt. Hope',
      'Mt. Lambert',
      'Orange Grove Estates',
      'Paria',
      'Petit Bourg',
      'Piarco',
      'Salybia',
      'San Juan',
      'San Raphael',
      'Sangre Chiquito',
      'Sangre Grande',
      'Sans Souci',
      'Santa Cruz',
      'Santa Rosa',
      'St. Augustine',
      'St. Joseph',
      'Tacarigua',
      'Toco',
      'Trincity',
      'Tunapuna',
      'Valencia',
      'Valsayn',
      'Wallerfield',
    ],
  },
  'North West': {
    name: 'North West',
    areas: [
      'Alyce Glen',
      'Bayshore',
      'Bayside',
      'Bayview',
      'Belmont',
      'Blue Basin',
      'Blue Range',
      'Buoys',
      'Carenage',
      'Cascade',
      'Chaguaramas',
      'Cocorite',
      'Diamond Vale',
      'Diego Martin',
      'East Dry River',
      'Ellerslie Park',
      'Fairways',
      'Federation Park',
      'Fort George',
      'Gasparee Island',
      'Gasper Grande',
      'Glencoe',
      'Goodwood Gardens',
      'Goodwood Heights',
      'Goodwood Park',
      'Haleland Park',
      'Hillsboro',
      'Lady Chancellor',
      'Laventille',
      'Long Circular',
      'Maraval',
      'Moka',
      'Monos Island',
      'Morvant',
      'Mucurapo',
      'Newtown',
      'Paramin',
      'Perseverance',
      'Petit Valley',
      'Point Cumana',
      'Port of Spain',
      'Shorelands',
      "St. Ann's",
      'St. Clair',
      'St. James',
      'Victoria Gardens',
      'Westmoorings',
      'Woodbrook',
    ],
  },
  'South East': {
    name: 'South East',
    areas: [
      'Galeota',
      'Guayaguayare',
      'Mayaro',
      'Rio Claro',
      'Tableland',
      'Williamsville',
    ],
  },
  'South West': {
    name: 'South West',
    areas: [
      'Aripero',
      'Avocat',
      'Barrackpore',
      'Bel Air',
      'Brode Narve',
      'Caratal',
      'Cedros',
      'Chatam',
      'Claxton Bay',
      'Cocoyea',
      'Cross Crossing',
      'Debe',
      'Dow Village',
      'Duncan Village',
      'Erin',
      'Esperance',
      'Fyzabad',
      'Gasparillo',
      'Gopaul Lands',
      'Granville',
      'Gulf View',
      'Hermitage',
      'La Brea',
      'La Romain',
      'Marabella',
      'Mootoo Lands',
      'Moruga',
      'Otaheite',
      'Palmiste',
      'Palo Seco',
      'Penal',
      'Phillipine',
      'Plaisance Park',
      'Point Fortin',
      'Pointe-a-Pierre',
      'Princes Town',
      'Retrench Village',
      'Rousillac',
      'San Fernando',
      'Siparia',
      'South Oropouche',
      'St. Joseph Village',
      'Ste. Madeleine',
      'Union Hall',
      'Vistabella',
      'Woodland',
    ],
  },
  Tobago: {
    name: 'Tobago',
    areas: [
      'Arnos Vale',
      'Bacolet',
      'Bethany',
      'Black Rock',
      'Bon Accord',
      'Buccoo',
      'Canaan',
      'Carnbee',
      'Castara',
      'Concordia',
      'Courland',
      'Crown Point',
      "Englishman's Bay",
      'Goodwood',
      'Grafton',
      'Grange',
      'Hope Estate',
      'Lambeau',
      'Les Coteaux',
      "Little Englishman's Bay",
      "Louis d'Or",
      'Lowlands',
      "Mary's Hill",
      'Mason Hall',
      'Moriah',
      'Mt Pleasant',
      'Mt Irvine',
      'Mt. St. George',
      'Orange Hill',
      'Parlatuvier',
      'Plymouth',
      'Prospect',
      'Riseland',
      'Roxborough',
      'Samaan Grove',
      'Scarborough',
      'Sherwood Park',
      'Shirvan Road',
      'Signal Hill',
      'Speyside',
      'Tobago Plantations',
    ],
  },
};

export const REGIONS = Object.keys(TRINIDAD_TOBAGO_LOCATIONS);

export function getAreasForRegion(region: string): string[] {
  return TRINIDAD_TOBAGO_LOCATIONS[region]?.areas || [];
}

export function getAllAreas(): string[] {
  return Object.values(TRINIDAD_TOBAGO_LOCATIONS)
    .flatMap(location => location.areas)
    .sort((a, b) => a.localeCompare(b));
}

export function findRegionByArea(area: string): string | null {
  for (const [region, data] of Object.entries(TRINIDAD_TOBAGO_LOCATIONS)) {
    if (data.areas.some(a => a.toLowerCase() === area.toLowerCase())) {
      return region;
    }
  }
  return null;
}

export function searchLocations(query: string): { region: string; area: string }[] {
  const results: { region: string; area: string }[] = [];
  const lowerQuery = query.toLowerCase();

  for (const [region, data] of Object.entries(TRINIDAD_TOBAGO_LOCATIONS)) {
    for (const area of data.areas) {
      if (area.toLowerCase().includes(lowerQuery)) {
        results.push({ region, area });
      }
    }
  }

  return results;
}
